config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :gyms do
    resources :coaches do
      get :reservation
    end
  end

  match "jsonload", to: "coaches#jsonload", via:[:get, :post]
  match "jsonsave", to: "coaches#jsonsave", as: "jsonsave", via:[:get, :post]

  resources :coaches

  namespace :account do
    resources :products
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :home, only: [:index]

  namespace :admin do
    resources :products
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :coaches
    resources :gyms
  end

  resources :carts do
    collection do
      delete :clean
    end
  end

  resources :items, controller: "cart_items"

end

app/models/gym.rb
class Gym < ActiveRecord::Base
  has_many :coaches
  has_one :photo

  default_scope -> { order('RANDOM()') }
  accepts_nested_attributes_for :photo
end

app/controllers/admin/gyms_controller.rb
class Admin::GymsController < ApplicationController

  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required

  def index
    @gym = Gym.all
  end

end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :authenticate_user!

  def index
    @gym = Gym.all
  end

  def show
    @gyms = Gym.find(params[:id])
  end

  def new
    @gyms = Gym.new
    @photo = @gyms.build_photo
  end

  def create
    @gyms = Gym.create(gyms_params)

    if @gyms.save
      redirect_to gyms_path
    else
      render :new
    end
  end

  def edit
    @gyms = Gym.find(params[:id])

    if @gyms.photo.present?
      @photo = @gyms.photo
    else
      @photo = @gyms.build_photo
    end
  end

  def update
    @gyms = Gym.find(params[:id])

    if @gyms.update(gyms_params)
      redirect_to gyms_path, notice: "修改資訊成功"
    else
      render :edit
    end
  end

  def destroy
    @gyms = Gym.find(params[:id])
    @gyms.destroy
    redirect_to gyms_path, alert: "資訊已刪除"
  end

  private

  def gyms_params
    params.require(:gym).permit(:name, :phone, :address, :introduction, photo_attributes: [:image, :id])
  end
end

app/helpers/admin/gyms_helper.rb
module Admin::GymsHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/admin/gyms/index.html.erb
<h2>健身房列表</h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增健身房", new_gym_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>名稱</th>
      <th>電話</th>
      <th>地址</th>
      <th>資訊</th>
      <th width="100">功能</th>
    </tr>
  </thead>
  <tbody>
    <% @gym.each do |gyms| %>

    <tr>
      <td> <%= gyms.id %> </td>
      <td> <%= gyms.name %> </td>
      <td> <%= gyms.address %> </td>
      <td> <%= gyms.phone %> </td>
      <td> <%= gyms.introduction %> </td>
      <td>
          <%= link_to("修改", edit_gym_path(gyms), class: "btn btn-primary" ) %>
        <br>
        <br>
          <%= link_to("刪除", gym_path(gyms), class: "btn btn-danger", 
                          method: :delete, data: { confirm: "Are you sure?" } )%>
        </td>
    </tr>
  </tbody>
  <% end %>
</table>