config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :gyms do
    resources :coaches do
      get :reservation
    end
  end

  match "jsonload", to: "coaches#jsonload", via:[:get, :post]
  match "jsonsave", to: "coaches#jsonsave", as: "jsonsave", via:[:get, :post]

  resources :coaches

  namespace :account do
    resources :products
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :home, only: [:index]

  namespace :admin do
    resources :products
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :coaches
    resources :gyms
  end

  resources :carts do
    collection do
      delete :clean
    end
  end

  resources :items, controller: "cart_items"

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_one :photo

  accepts_nested_attributes_for :photo
end

app/controllers/account/products_controller.rb
class Account::ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = current_user.products.all
  end

  def new
    @product = current_user.products.new
    @photo = @product.build_photo
  end

  def edit
    @product = Product.find(params[:id])

    if @product.photo.present?
      @photo = @product.photo
    else
      @photo = @product.build_photo
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to account_products_path
    else
      render :edit
    end
  end

  def create
    @product = current_user.products.new(product_params)

    if @product.save
      redirect_to account_products_path
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path(@product), alert: "商品已下架"
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, photo_attributes: [:image, :id])
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  
  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required

   def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @photo = @product.build_photo
  end

  def edit
    @product = Product.find(params[:id])

     if @product.photo.present?
       @photo = @product.photo
     else
       @photo = @product.build_photo
     end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  private

  def product_params
      params.require(:product).permit(:title, :description, :quantity, :price, photo_attributes: [:image, :id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, alert: "商品已下架"
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.items.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已成功將 #{@product.title} 加入購物車"
    else
      flash[:warning] = "你的購物車內已有此物品"
    end
    redirect_to :back
  end
end

app/helpers/account/products_helper.rb
module Account::ProductsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.label("商品名稱") %>
    <%= f.text_field :title %>
  </div>

  <div class="group">
    <%= f.label("商品資訊") %>
    <%= f.text_area :description %>
  </div>

  <div class="group">
    <%= f.label("數量") %>
    <%= f.text_field :quantity %>
  </div>

  <div class="group">
    <%= f.label("價錢") %>
    <%= f.text_field :price %>
  </div>

  <div class="form-group">
    <%= f.simple_fields_for :photo do |c| %>
      <%= c.input :image , as: :file %>
    <% end %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/edit.html.erb
<h2> 修改商品資訊 </h2>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<h2> 二手器材列表 </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增商品", new_account_product_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">商品圖片</th>
      <th>商品名稱</th>
      <th>商品資訊</th>
      <th>價格</th>
      <th width="100">功能</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td> <%= product.id %> </td>
        <td>
          <%= link_to product_path(product) do %>
            <% if product.photo.present? %>
              <%= image_tag(product.photo.image.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= product.title %>
        </td>
        <td>
          <%= product.description %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <%= link_to("修改", edit_admin_product_path(product), class: "btn btn-primary" ) %>
        <br>
        <br/>
          <%= link_to("下架", product_path(product), class: "btn btn-danger", 
                          method: :delete, data: { confirm: "Are you sure?" } )%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2> 新增商品資訊 </h2>

<%= render 'form' %>