config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :gyms do
    resources :coaches do
      get :reservation
    end
  end

  match "jsonload", to: "coaches#jsonload", via:[:get, :post]
  match "jsonsave", to: "coaches#jsonsave", as: "jsonsave", via:[:get, :post]

  resources :coaches

  namespace :account do
    resources :products
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :home, only: [:index]

  namespace :admin do
    resources :products
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :coaches
    resources :gyms
  end

  resources :carts do
    collection do
      delete :clean
    end
  end

  resources :items, controller: "cart_items"

end

app/models/gym.rb
class Gym < ActiveRecord::Base
  has_many :coaches
  has_one :photo

  default_scope -> { order('RANDOM()') }
  accepts_nested_attributes_for :photo
end

app/controllers/admin/gyms_controller.rb
class Admin::GymsController < ApplicationController

  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required

  def index
    @gym = Gym.all
  end

end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :authenticate_user!

  def index
    @gym = Gym.all
  end

  def show
    @gyms = Gym.find(params[:id])
  end

  def new
    @gyms = Gym.new
    @photo = @gyms.build_photo
  end

  def create
    @gyms = Gym.create(gyms_params)

    if @gyms.save
      redirect_to gyms_path
    else
      render :new
    end
  end

  def edit
    @gyms = Gym.find(params[:id])

    if @gyms.photo.present?
      @photo = @gyms.photo
    else
      @photo = @gyms.build_photo
    end
  end

  def update
    @gyms = Gym.find(params[:id])

    if @gyms.update(gyms_params)
      redirect_to gyms_path, notice: "修改資訊成功"
    else
      render :edit
    end
  end

  def destroy
    @gyms = Gym.find(params[:id])
    @gyms.destroy
    redirect_to gyms_path, alert: "資訊已刪除"
  end

  private

  def gyms_params
    params.require(:gym).permit(:name, :phone, :address, :introduction, photo_attributes: [:image, :id])
  end
end

app/helpers/admin/gyms_helper.rb
module Admin::GymsHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_form.html.erb
<%= simple_form_for @gyms do |f| %>

  <div class="group">
    <%= f.input :name %>
  </div>

  <div class="group">
    <%= f.input :phone %>
  </div>

  <div class="group">
    <%= f.input :address %>
  </div>

  <div class="group">
    <%= f.input :introduction %>
  </div>

  <div class="form-group">
    <%= f.simple_fields_for :photo do |c| %>
      <%= c.input :image , as: :file %>
    <% end %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/gyms/edit.html.erb
<h2> 修改健身房資訊 </h2>

<%= render 'form' %>

app/views/gyms/index.html.erb
 <h2><center>健身房總覽</center></h2>
 <br>
 <div class="container">
  <% @gym.each do |gyms| %>
    <div class="col-xs-6 col-md-3">
      <%= link_to gym_path(gyms) do %>
        <% if gyms.photo.present? %>
          <%= image_tag(gyms.photo.image.thumb.url, class: "thumbnail") %>
        <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
      <% end %>

      <%= gyms.name %>
    </div>
  <% end %>
</div>

app/views/gyms/new.html.erb
<h2> 新增健身房資訊 </h2>

<%= render 'form' %>

app/views/gyms/show.html.erb
<div class="container-fluid">
<div class="row">
  <div class="col-md-6">
    <% if @gyms.photo.present? %>
      <%= image_tag(@gyms.photo.image.medium.url, class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>
    <div class="col-md-6">
      <h3> <%=@gyms.name%> </h3>
       <p>地址: <%= @gyms.address %></p>
       <p>電話: <%= @gyms.phone %></p>
       <p>資訊: <%= @gyms.introduction %></p>
      <hr>
      <h3>本館教練</h3>
 <div class="row">
  <% @gyms.coaches.each do |coach| %>
    <div class="col-xs-6 col-md-6">
    <p>姓名: <%= coach.name %></p>
    <p>擅長: <%= coach.major %></p>
    <p>簡介: <%= coach.introduction %></p>
    <p><%= link_to '預約', gym_coach_reservation_path(@gyms, coach), class: "btn btn-info" %></p>
    </div>
  <% end %>
</div>
  <% @gym = Gym.find_by(params[:gym_id]) %>
    <br>
    <% if current_user.admin? %>
       <%= link_to("新增教練", new_gym_coach_path(@gym), class: "btn btn-primary") %>
    <% end %>
       <%= link_to("上一頁", gyms_path, class: "btn btn-default") %>
  </div>
</div>
</div>