config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :gyms do
    resources :coaches do
      get :reservation
    end
  end

  match "jsonload", to: "coaches#jsonload", via:[:get, :post]
  match "jsonsave", to: "coaches#jsonsave", as: "jsonsave", via:[:get, :post]

  resources :coaches

  namespace :account do
    resources :products
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :home, only: [:index]

  namespace :admin do
    resources :products
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :coaches
    resources :gyms
  end

  resources :carts do
    collection do
      delete :clean
    end
  end

  resources :items, controller: "cart_items"

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.save
  end

  def total_price
    sum = 0

    cart_items.each do |cart_item|
+      sum = sum + (cart_item.product.price * cart_item.quantity)
    end

    sum
  end

  def clean!
    cart_items.destroy_all
  end

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  belongs_to :gym
  has_one :photo

  has_many :reservations
  accepts_nested_attributes_for :photo
end

app/models/coach_schedule.rb
class CoachSchedule < ActiveRecord::Base
end

app/models/gym.rb
class Gym < ActiveRecord::Base
  has_many :coaches
  has_one :photo

  default_scope -> { order('RANDOM()') }
  accepts_nested_attributes_for :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :gym
  belongs_to :coach
  belongs_to :product
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_one :photo

  accepts_nested_attributes_for :photo
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :coach
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :products

  def admin?
    is_admin
  end

  def to_admin
    self.update_columns(is_admin: true)
  end

  def to_normal
    self.update_columns(is_admin: false)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
    current_cart.clean!
    flash[:warning] = "已清空購物車"
    redirect_to carts_path
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :authenticate_user!

  def index
    @coaches = Coach.all
  end

  def show
    @coach = Coach.find(params[:id])
  end

  def new
    @gym = Gym.find(params[:gym_id])
    @coach = @gym.coaches.new
    @photo = @coach.build_photo
  end

  def create
    @gym = Gym.find(params[:gym_id])
    @coach = @gym.coaches.new(coach_params)

    if @coach.save
      redirect_to gym_coaches_path
    else
      render :new
    end
  end

  def edit
    @gym = Gym.find(params[:gym_id])
    @coach = @gym.coaches.find(params[:id])

    if @coach.photo.present?
      @photo = @coach.photo
    else
      @photo = @coach.build_photo
    end
  end

  def update
    @gym = Gym.find(params[:gym_id])
    @coach = @gym.coaches.find(params[:id])

    if @coach.update(coach_params)
      redirect_to gym_coaches_path, notice: "資訊修改成功"
    else
      render :edit
    end
  end

  def destroy
    @gym = Gym.find(params[:gym_id])
    @coach = @gym.coaches.find(params[:id])
    @coach.destroy
    redirect_to gym_coaches_path, alert: "資訊已刪除"
  end

  def reservation
    @coach = Coach.find(params[:coach_id])
  end

  def jsonload
  end

  private

  def coach_params
    params.require(:coach).permit(:name, :major, :introduction, :gym_id, photo_attributes: [:image, :id])
  end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :authenticate_user!

  def index
    @gym = Gym.all
  end

  def show
    @gyms = Gym.find(params[:id])
  end

  def new
    @gyms = Gym.new
    @photo = @gyms.build_photo
  end

  def create
    @gyms = Gym.create(gyms_params)

    if @gyms.save
      redirect_to gyms_path
    else
      render :new
    end
  end

  def edit
    @gyms = Gym.find(params[:id])

    if @gyms.photo.present?
      @photo = @gyms.photo
    else
      @photo = @gyms.build_photo
    end
  end

  def update
    @gyms = Gym.find(params[:id])

    if @gyms.update(gyms_params)
      redirect_to gyms_path, notice: "修改資訊成功"
    else
      render :edit
    end
  end

  def destroy
    @gyms = Gym.find(params[:id])
    @gyms.destroy
    redirect_to gyms_path, alert: "資訊已刪除"
  end

  private

  def gyms_params
    params.require(:gym).permit(:name, :phone, :address, :introduction, photo_attributes: [:image, :id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @gyms = Gym.limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end

  def render_cart_items_count(cart)
    cart.cart_items.count
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/common/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default" role="navigation">
    <div class="container">
              <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
              <a class="navbar-brand" href="<%= root_path %>">GoGoGym</a>
          </div>

           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-left">
                <li>
                  <%= link_to("健身房", gyms_path ) %>
                </li>
                <li>
                  <%= link_to("現有教練", coaches_path) %>
                </li>
                <li>
                  <%= link_to("二手器材", products_path ) %>
                </li>
              </ul>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to carts_path do  %>
                  購物車 <i class="fa fa-shopping-cart"> </i> ( <%= render_cart_items_count(current_cart) %> )
                <% end %>
              </li>

              <% if !current_user %>
                <li> <%= link_to("登入", new_user_session_path) %> </li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Hi!, <%= current_user.name %>
                    <b class="caret"></b>
                  </a>
                   <ul class="dropdown-menu">

                    <% if current_user.admin? %>
                      <li>
                        <%= link_to("Admin 選單", admin_products_path ) %>
                      </li>
                    <% end %>
                     <li>
                       <%= link_to("我的商品", account_products_path ) %>
                     </li>
                     <li>
                      <%= link_to("帳號設定", edit_user_registration_path )%>
                    </li>
                    <li>
                      <%= link_to("登出", destroy_user_session_path, method: :delete ) %>
                    </li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>

app/views/gymnasia/_form.html.erb
<%= simple_form_for @gymnasia do |f| %>

  <div class="group">
    <%= f.input :name %>
  </div>

  <div class="group">
    <%= f.input :phone %>
  </div>

  <div class="group">
    <%= f.input :address %>
  </div>

  <div class="group">
    <%= f.input :introduction %>
  </div>

  <div class="form-group">
    <%= f.simple_fields_for :photo do |c| %>
      <%= c.input :image , as: :file %>
    <% end %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/gymnasia/index.html.erb
 <h3><center>健身房資訊</center></h3>
 <br>
 <div class="row">
  <% @gymnasium.each do |gymnasia| %>
    <div class="col-xs-6 col-md-3">
      <%= link_to gymnasium_path(gymnasia) do %>
        <% if gymnasia.photo.present? %>
          <%= image_tag(gymnasia.photo.image.thumb.url, class: "thumbnail") %>
        <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
      <% end %>
      <%= gymnasia.name %>
    </div>
  <% end %>
</div>

app/views/gymnasia/show.html.erb
  </div>

<div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        
                        <li>
                            <a href="<%= "#" %>"> 教練訊息 </a>
                        </li>
                        <li>
                            <a href="<%= "#" %>"> 教學照片 </a>
                        </li>
                        <li>
                            <a href="<%= "#" %>"> 運動夥伴 </a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                      <br>
                        <%= yield %>
                    </div>

<div class="row">
  <div class="col-md-6">
    <% if @gymnasia.photo.present? %>
      <%= image_tag(@gymnasia.photo.image.medium.url, class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>
    <div class="col-md-6">
      <h3> <%=@gymnasia.name%> </h3>
       <p>地址: <%= @gymnasia.address %></p>
       <p>電話: <%= @gymnasia.phone %></p>
       <p>資訊: <%= @gymnasia.introduction %></p>

    <br>
       <%= link_to("上一頁", gymnasia_path, class: "btn btn-default") %>
  </div>
</div>